[package]
name = "chia-inspect"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
clap.workspace = true
serde_json.workspace = true
chia-inspect-core = { path = "../chia-inspect-core" }
