[package]
name = "clvm-workbench"
version = "1.0.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
clap.workspace = true
hex.workspace = true
chialisp.workspace = true
clvmr.workspace = true
